spring:
  datasource:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    password: ''
    platform: h2
    schema: classpath*:schema-h2.sql
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: test
